### ISSUE TITLE
GAMES_000J Cleanup

### ISSUE THREAD

**Issue by glocka** [sw20-tug/SWT-Morning-2#52]
**TODO**

- [x]  Check existing TC
- [x] Test on different devices (resolutions, notch,...)
- [x] Write further/missing TC
- [x] Check test coverage
